name: nend_plugin
description: nend plugin that shows banner ads, interstitial ads and video ads.
version: 1.0.2
homepage: https://github.com/fan-ADN/nendSDK-Flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.nend.nendplugin
        pluginClass: NendPlugin
      ios:
        pluginClass: NendPlugin
